Numpy

In [29]:
import numpy as np
import pandas as pd

In [3]:
one_dime_array = np.array([1.5,2.5,3.6,4.2,5.5,6.3,9.6,4.5])
print(one_dime_array)

[1.5 2.5 3.6 4.2 5.5 6.3 9.6 4.5]


In [4]:
two_dime_array = ([[3,5],[2,1],[3,8]])
print(two_dime_array)

[[3, 5], [2, 1], [3, 8]]


In [12]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((7,), dtype = int)

array([1, 1, 1, 1, 1, 1, 1])

In [18]:
sequence_of_integer = np.arange(16,25)
print(sequence_of_integer)

[16 17 18 19 20 21 22 23 24]


In [21]:
random_int = np.random.randint(low=200, high=230, size=(7,))
print(random_int)

[226 224 216 217 226 229 204]


In [22]:
random_float = np.random.random(6,)
print(random_float)

[0.74219007 0.84530372 0.85092393 0.95647469 0.83169041 0.49793408]


In [24]:
rng = np.random.default_rng()
rng.random(size=10)

array([0.92971706, 0.99409617, 0.93472238, 0.50574874, 0.69882179,
       0.5824583 , 0.39347015, 0.42905147, 0.99936441, 0.70428518])

In [28]:
rng.uniform(1, 4, size=10)

array([3.91950787, 2.79880352, 3.58690794, 1.74584574, 2.12386693,
       3.24742794, 1.31381789, 1.68921779, 1.17728839, 2.83218852])

Task 1: Create a Linear Dataset
Your goal is to create a simple dataset consisting of a single feature and a label as follows:

Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
Assign 15 values to a NumPy array named label such that:
   label = (3)(feature) + 4
For example, the first value for label should be:

  label = (3)(6) + 4 = 22

In [30]:
feature = np.arange(6,21) # write your code here
print(feature)
label = (feature * 3) + 4   # write your code here
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Task 2: Add Some Noise to the Dataset
To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.

In [31]:
noise = (np.random.random([15]) * 4) - 2    # write your code here
print(noise)
label = label + noise    # write your code here
print(label)

[ 0.0954327  -1.49461726 -0.38078928  1.95632531  1.49542483 -0.7335952
 -1.65088686  0.73229206 -0.95192484  0.8622042  -1.95865261 -0.39778697
 -1.75941126  1.40738949 -0.4905878 ]
[22.0954327  23.50538274 27.61921072 32.95632531 35.49542483 36.2664048
 38.34911314 43.73229206 45.04807516 49.8622042  50.04134739 54.60221303
 56.24058874 62.40738949 63.5094122 ]


Pandas

In [34]:
#create and populate the array
my_data = np.array([[10,4],[20,7],[30,9],[40,8],[35,1]])

#Python list that holds the name of the two columns
my_column_names = ['temperature','activity']

#create a dataframe
my_dataframe = pd.DataFrame(data=my_data, columns= my_column_names)

print(my_dataframe)

   temperature  activity
0           10         4
1           20         7
2           30         9
3           40         8
4           35         1


Adding new column to the dataframe-

In [35]:
my_dataframe["adjusted"] = my_dataframe["activity"] + 2
print(my_dataframe)

   temperature  activity  adjusted
0           10         4         6
1           20         7         9
2           30         9        11
3           40         8        10
4           35         1         3


Specifying a subset of dataframe

In [36]:
print("Rows #1 #2 and #3:")
print(my_dataframe.head(3), '\n')

Rows #1 #2 and #3:
   temperature  activity  adjusted
0           10         4         6
1           20         7         9
2           30         9        11 



In [37]:
print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

Row #2:
   temperature  activity  adjusted
2           30         9        11 



In [38]:
print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           20         7         9
2           30         9        11
3           40         8        10 



In [39]:
print("Column 'temperature':")
print(my_dataframe['temperature'])

Column 'temperature':
0    10
1    20
2    30
3    40
4    35
Name: temperature, dtype: int32


In [40]:
# Create a Python list that holds the names of the four columns.
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

# Create a 3x4 numpy array, each cell populated with a random integer.
my_data = np.random.randint(low=0, high=101, size=(3, 4))

# Create a DataFrame.
df = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(df)

# Print the value in row #1 of the Eleanor column.
print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])

# Create a column named Janet whose contents are the sum
# of two other columns.
df['Janet'] = df['Tahani'] + df['Jason']

# Print the enhanced DataFrame
print(df)

   Eleanor  Chidi  Tahani  Jason
0       70     49      76     46
1       43     31      87     63
2       16     10      45     87

Second row of the Eleanor column: 43

   Eleanor  Chidi  Tahani  Jason  Janet
0       70     49      76     46    122
1       43     31      87     63    150
2       16     10      45     87    132


In [41]:
# Create a reference by assigning my_dataframe to a new variable.
print("Experiment with a reference:")
reference_to_df = df

# Print the starting value of a particular cell.
print("  Starting value of df: %d" % df['Jason'][1])
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Jason'][1])

# Modify a cell in df.
df.at[1, 'Jason'] = df['Jason'][1] + 5
print("  Updated df: %d" % df['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

# Create a true copy of my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

Experiment with a reference:
  Starting value of df: 63
  Starting value of reference_to_df: 63

  Updated df: 68
  Updated reference_to_df: 68


Experiment with a true copy:
  Starting value of my_dataframe: 7
  Starting value of copy_of_my_dataframe: 7

  Updated my_dataframe: 10
  copy_of_my_dataframe does not get updated: 7
